[project]
name = "local-gpt"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "chainlit>=2.6.0",
    "ollama>=0.5.1",
    "pydantic==2.10.1",
]
