[project]
name = "local-gpt"
version = "0.1.0"
description = "Local GPT with PDF Q&A using Chainlit"
requires-python = ">=3.11"
dependencies = [
    "chainlit>=1.0.0",
    "python-dotenv>=1.0.0",
    "chromadb>=0.4.0",
    "sentence-transformers>=2.2.0",
    "PyPDF2>=3.0.0",
    "ollama>=0.5.1",
]
